ALTER TABLE `payment` MODIFY COLUMN `OWN_NUM_SR` VARCHAR(30) COMMENT 'Лицевой счет в обслуж. организации';

ALTER TABLE `payment` MODIFY COLUMN `CODE3_1` INTEGER(10) COMMENT 'Код тарифа оплаты жилья';
ALTER TABLE `payment` MODIFY COLUMN `CODE3_2` INTEGER(10) COMMENT 'Код тарифа отопления';
ALTER TABLE `payment` MODIFY COLUMN `CODE3_3` INTEGER(10) COMMENT 'Код тарифа горячего водоснабжения';
ALTER TABLE `payment` MODIFY COLUMN `CODE3_4` INTEGER(10) COMMENT 'Код тарифа холодного водоснабжения';
ALTER TABLE `payment` MODIFY COLUMN `CODE3_5` INTEGER(10) COMMENT 'Код тарифа - газоснабжение';
ALTER TABLE `payment` MODIFY COLUMN `CODE3_6` INTEGER(10) COMMENT 'Код тарифа-электроэнергии';
ALTER TABLE `payment` MODIFY COLUMN `CODE3_7` INTEGER(10) COMMENT 'Код тарифа - вывоз мусора';
ALTER TABLE `payment` MODIFY COLUMN `CODE3_8` INTEGER(10) COMMENT 'Код тарифа - водоотведение';
ALTER TABLE `payment` MODIFY COLUMN `CODE3_17` INTEGER(10);
ALTER TABLE `payment` MODIFY COLUMN `CODE3_18` INTEGER(10);
ALTER TABLE `payment` MODIFY COLUMN `CODE3_19` INTEGER(10);
ALTER TABLE `payment` MODIFY COLUMN `CODE3_20` INTEGER(10);
ALTER TABLE `payment` MODIFY COLUMN `CODE3_21` INTEGER(10);
ALTER TABLE `payment` MODIFY COLUMN `CODE3_22` INTEGER(10);
ALTER TABLE `payment` MODIFY COLUMN `CODE3_23` INTEGER(10);
ALTER TABLE `payment` MODIFY COLUMN `CODE3_24` INTEGER(10);
ALTER TABLE `payment` MODIFY COLUMN `CODE3_25` INTEGER(10);
ALTER TABLE `payment` MODIFY COLUMN `CODE3_26` INTEGER(10);
ALTER TABLE `payment` MODIFY COLUMN `CODE3_50` INTEGER(10);
ALTER TABLE `payment` MODIFY COLUMN `CODE3_60` INTEGER(10);
ALTER TABLE `payment` MODIFY COLUMN `CODE3_70` INTEGER(10);

INSERT INTO `update` (`version`) VALUE ('0.9.3');
